trigger:
  - main

pool:
  name: maquinapessoal

steps:
  - script: npm install
    displayName: 'Instalando dependencias'

  - script: npx cypress --version
    displayName: 'Verificando versão do Cypress'

  - script: npx cypress run --headless --browser edge --verbose
    displayName: 'Rodando testes Cypress'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'results/junit-*.xml'
      testRunTitle: 'Resultados Cypress'
      testRunner: 'JUnit'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'cypress/evidences'
      artifact: 'CypressEvidences'
      publishLocation: 'pipeline'