trigger:
  - main

pool:
  name: maquinapessoal

steps:
  - script: npm install
    displayName: 'Instalando dependencias'

  - script: npx cypress run
    displayName: 'Rodando testes'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'results/junit-*.xml'
      testRunTitle: 'Resultados Cypress'
      testRunner: 'JUnit'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'cypress/evidences'
      artifact: 'CypressEvidences'
      publishLocation: 'pipeline'
