trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'

steps:
  - task: Checkout@1

  - task: NodeTool@1
    inputs:
      versionSpec: '16.x'

  - script: npm install
    displayName: 'Install Dependencies'

  - script: npx cypress run
    displayName: 'Run Cypress Tests'
